### ISSUE TITLE
Centering the Clock

### ISSUE THREAD

**Issue by Mousecop** [pughpugh/react-countdown-clock#23]
Hello, I have a question/ issue about the clock not being able to center correctly due to what seems the absolute positioning of the second <canvas?> element. Is there any clear way to fix this or adjust to what I need? Thank you.

**Comment by pughpugh** [comment]
Hi,

Have you tried using a wrapping element like in the [example](http://pughpugh.github.io/react-countdown-clock/)?

```html
<div id="parappa">
  <div data-reactroot="" class="react-countdown-clock">
    <canvas width="300" height="300" style="position: absolute;"></canvas>
    <canvas width="300" height="300" style="position: absolute;"></canvas>
  </div>
</div>
```
```css
#parappa {
    position: absolute;
    top: 50%;
    left: 50%;
    width: 300px;
    height: 300px;
    margin: -150px 0 0 -150px;
}
```
